Enable basic support for `worktreeconfig` to unblock sparse checkout.
stacked-git/stgit pull request #234
Opened 2022-11-15 23:39 UTC by NonLogicalDev

`libgit2` library by default fails any operation if it encounters any unrecognised extensions configured in a repo, as per Git documentation.

ref: https://git-scm.com/docs/repository-version

> If a version-1 repository specifies any extensions.* keys that the
> running git has not implemented, the operation MUST NOT proceed.
> Similarly, if the value of any known key is not understood by the
> implementation, the operation MUST NOT proceed.

If a repository is using a sparse checkout mode it force enables the `worktreeconfig` extensions which allows setting configuration in repo on a per worktree basis, to enable some of the sparse checkout functionality.

Since `stg` is using `libgit2` library only as an interface to object database and for looking up alias lookup from git configuration (i.e. Read Only operation) and uses git cli for everything else, it is relatively safe to ignore per worktree git configuration.

This patch adds `worktreeconfig` extension to the `libgit2` extension whitelist.

2022-11-16 15:23 UTC, jpgrayson requested changes
One thing I still don't understand is how the tests in `t7000-sparse-checkout.sh` pass without this change? It seems like as long as an associated worktree is not added with `git worktree add`, then libgit2 is okay with `extensions.worktreeConfig` being in `.git/config`.

It would be helpful if there was a test, either in `t7000-sparse-checkout.sh` or in a new test script that triggers the problem that this change solves.

2022-11-17 00:40 UTC, NonLogicalDev commented on Cargo.toml
> +once_cell = "~1.14"
fair point will take this out, this was leftover part of my experiment to use a singleton based initialization.
But I was sadly incapable of figuring out a way to code it that appeased the borrow checker.

2022-11-17 00:41 UTC, NonLogicalDev commented on Cargo.toml
> +git2-ext-worktreeconfig-support = []
I was thinking of keeping it there for safety. I suppose a better way might be to have it be guarded with a config flag.

2022-11-17 00:47 UTC, NonLogicalDev commented on src/main.rs
> +
That sounds good to me. I did not notice the slowdown but I get where you are coming from.
Ideally this should be something of a global helper singleton function, called upon needing to access the repo for first time.

2022-11-17 03:25 UTC, NonLogicalDev commented
@jpgrayson I figured out why `t7000-sparse-checkout.sh` works and why our company monorepo does not.

It all has to do with `core.repositoryversion`. I dug in and found out that `core.repositoryversion` gets set to 1 whey the Object Hash is configured to be SHA256 rather than SHA1.

I threw together a test script that reproduces this issue:
https://gist.github.com/NonLogicalDev/29b55d855c8aaae0a641cd0dda2ec443

2022-11-17 14:03 UTC, jpgrayson approved these changes

2022-11-17 14:07 UTC, jpgrayson commented
Thank you for solving the mystery of the difference between `t7000-sparse-checkout.sh` and your environment! And for the test case. I will do a follow-on change to integrate the test case into StGit's test suite.

2022-11-17 14:08 UTC, merged

2022-11-17 16:24 UTC, NonLogicalDev commented
Huge Thanks @jpgrayson! Super grateful for your support and patience on this project!

2022-11-17 17:12 UTC, jpgrayson commented
Thank you @NonLogicalDev for doing all the legwork to figure out this problem.